"""Code to solve problem #22 of Project Euler.  Problem reads as follows:

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

import math

def triangle_number_generator():
    y,x = 1, 1
    while True:
        x += 1
        y += x
        yield y

def divisor_counter(product):
    counter=0
    for x in range(1, int(math.sqrt(product)+1)):        
        if product % x == 0:
            counter += 1
    return 2*counter


number_divisors = 0
t = triangle_number_generator()

while number_divisors <= 500:
    current_triangle_number = next(t)
    number_divisors = divisor_counter(current_triangle_number)

print(current_triangle_number)